### ISSUE TITLE
EVKX.net norwegian site

### ISSUE THREAD

**Issue by TheTechArch** [evkx/evkx.github.io#2]
Translate the site to Norwegian and update text where Norwegian conditions are relevant.

## Tasks

- [ ] Translate model description
- [ ] Translate model specifications
- [ ] Translate model range
- [ ] Translate model charging info
- [ ] Translate model gallery
- [ ] Translate model overview 
- [ ] Translate Brand overview 
- [ ] Translate Brands overview
