### ISSUE TITLE
Top list for EVs

### ISSUE THREAD

**Issue by TheTechArch** [evkx/evkx.github.io#20]
## Description

We need an updated top list for most selling cars. It should include both a global list and country specific lists

## Requirements

- Should support a global and country-specific list
- Should contain information about the period the list is based on (month, last year ++) 
- Should contain a source of information
- Should contain info about date updated
- Should be possible to have several list per area. (last month, last year) 
- Should link to EV model when

## Task
- [ ] Define JSON dataformat for list
- [ ] Update site generation for list source
- [ ] Update model description for top sellers

**Comment by TheTechArch** [comment]
Added earlier, improved yesterday
